name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Renovate
        uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
